# Generated by Django 2.2.6 on 2020-01-18 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0005_auto_20200118_1452'),
        ('activity', '0011_auto_20191203_1749'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy', models.CharField(blank=True, max_length=20, null=True, verbose_name='学院')),
                ('grade', models.CharField(blank=True, max_length=20, null=True, verbose_name='年级')),
                ('clazz', models.CharField(blank=True, max_length=20, null=True, verbose_name='班级')),
                ('activity_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='活动名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('join_type', models.SmallIntegerField(choices=[(1, '参赛者'), (2, '观众'), (3, '工作人员')], verbose_name='参与类型')),
                ('status', models.BooleanField(default=False, verbose_name='是否签到签退成功')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activity.Activity', verbose_name='活动')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='join_activities', to='student.Student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生活动表',
                'verbose_name_plural': '学生活动表',
                'db_table': 'student_activities',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
                'db_table': 'log',
                'ordering': ('-created_at',),
            },
        ),
    ]
