# Generated by Django 2.2.6 on 2019-12-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_log_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivity',
            name='status',
            field=models.BooleanField(default=False, verbose_name='状态'),
        ),
    ]
