# Generated by Django 2.2.6 on 2020-01-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_studentactivity_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivity',
            name='credit_type',
            field=models.CharField(default='', max_length=20, verbose_name='学时类别'),
        ),
    ]
