# Generated by Django 2.2.6 on 2019-12-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_studentactivity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactivity',
            name='join_type',
            field=models.SmallIntegerField(choices=[(1, '参赛者'), (2, '观众'), (3, '工作人员')], verbose_name='参与类型'),
        ),
    ]
