# Generated by Django 2.2.6 on 2020-01-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20200118_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentactivity',
            options={'ordering': ('-create_time',), 'verbose_name': '学生活动表', 'verbose_name_plural': '学生活动表'},
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '报名'), (2, '签到成功'), (3, '签退成功')], default=1, verbose_name='参与状态'),
        ),
    ]
