# Generated by Django 2.2.6 on 2020-02-29 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_auto_20200229_1545'),
        ('operation', '0006_auto_20200120_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student_id', models.CharField(max_length=20, verbose_name='学号')),
                ('student_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('student_class', models.CharField(max_length=20, verbose_name='班级')),
                ('student_grade', models.CharField(max_length=20, verbose_name='年级')),
                ('student_academy', models.CharField(max_length=20, verbose_name='学院')),
                ('score', models.IntegerField(default=5, verbose_name='评论分数')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='activity.Activity', verbose_name='活动')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment',
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['student_id'], name='student_id_idx'),
        ),
    ]
