# Generated by Django 2.2.6 on 2020-03-02 12:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_auto_20200229_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('email', models.EmailField(max_length=254, verbose_name='反馈人邮箱')),
                ('name', models.CharField(max_length=20, verbose_name='反馈人姓名')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('is_fix', models.BooleanField(default=False, verbose_name='是否解决')),
                ('reply', models.CharField(default='', max_length=255, verbose_name='回复')),
            ],
            options={
                'verbose_name': '反馈',
                'verbose_name_plural': '反馈',
                'db_table': 'feedback',
                'ordering': ('-created_at',),
            },
        ),
    ]
