# Generated by Django 2.2.6 on 2020-03-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',), 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
