# Generated by Django 2.2.6 on 2020-06-08 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_auto_20200313_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactivity',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_students', to='activity.Activity', verbose_name='活动'),
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_activities', to='student.Student', verbose_name='学生'),
        ),
    ]
