# Generated by Django 2.2.6 on 2020-06-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_auto_20200608_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivity',
            name='is_verify',
            field=models.SmallIntegerField(choices=[(0, '未验证'), (1, '已验证')], default=1, verbose_name='是否验证'),
        ),
    ]
