# Generated by Django 2.2.6 on 2019-11-15 21:32

import ckeditor_uploader.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='活动id')),
                ('name', models.CharField(max_length=255, verbose_name='活动名称')),
                ('logo', models.ImageField(default='', upload_to='activity/logo/%Y/%m/%d/', verbose_name='活动图标')),
                ('file', models.FileField(blank=True, null=True, upload_to='activity/files/%Y/%m/%d/', verbose_name='活动策划表')),
                ('sponsor', models.CharField(max_length=255, verbose_name='主办方')),
                ('credit_type', models.CharField(choices=[('n', '未选择'), ('fl_credit', '法律'), ('wt_credit', '文体'), ('xl_credit', '心理'), ('cxcy_credit', '创新创业'), ('sxdd_credit', '思想道德')], default='n', max_length=20, verbose_name='学时类别')),
                ('time', models.CharField(max_length=255, verbose_name='活动时间')),
                ('place', models.CharField(default='', max_length=255, verbose_name='活动地点')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='报名截止日期')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='活动描述')),
                ('score_player', models.FloatField(default=0, verbose_name='参与者学时')),
                ('score_staff', models.FloatField(default=0, verbose_name='工作人员学时')),
                ('score_viewer', models.FloatField(default=0, verbose_name='观众学时')),
                ('is_verify', models.BooleanField(default=False, verbose_name='是否通过审核')),
                ('is_verifying', models.BooleanField(default=True, verbose_name='是否正在进行审核')),
                ('reason', models.CharField(default='', max_length=255, verbose_name='审核失败原因')),
                ('stop', models.BooleanField(default=False, verbose_name='是否截止')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 'activity_backend',
                'ordering': ('-created_at',),
            },
        ),
    ]
