# Generated by Django 2.2.6 on 2019-11-05 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='credit_type',
            field=models.CharField(choices=[('n', '未选择'), ('fl_credit', '法律'), ('wt_credit', '文体'), ('xl_credit', '心理'), ('cxcy_credit', '创新创业'), ('sxdd_credit', '思想道德')], default='n', max_length=20, verbose_name='学时类别'),
        ),
        migrations.AddField(
            model_name='activity',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='activity/%Y/%m/%d/', verbose_name='活动策划表'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
    ]
