# Generated by Django 2.2.6 on 2019-11-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20191115_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleActivity',
            fields=[
                ('uid', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='活动id')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='活动名称')),
                ('score_player', models.FloatField(blank=True, default=0, null=True, verbose_name='参与者学时')),
                ('score_staff', models.FloatField(blank=True, default=0, null=True, verbose_name='工作人员学时')),
                ('score_viewer', models.FloatField(blank=True, default=0, null=True, verbose_name='观众学时')),
                ('sponsor', models.CharField(blank=True, max_length=255, null=True, verbose_name='主办方')),
                ('time', models.CharField(blank=True, max_length=255, null=True, verbose_name='活动时间')),
                ('stop', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否截止')),
                ('nums', models.IntegerField(blank=True, default=0, null=True, verbose_name='参加人数')),
                ('place', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='活动地点')),
                ('logo', models.CharField(blank=True, max_length=255, null=True, verbose_name='活动图标')),
                ('credit_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='学时类别')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='报名截止日期')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 'activity',
                'ordering': ('-stop',),
            },
        ),
    ]
