# Generated by Django 2.2.6 on 2019-11-05 21:46

from django.db import migrations
import learntime.DjangoUeditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20191105_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='desc',
            field=learntime.DjangoUeditor.models.UEditorField(default='', verbose_name='活动内容'),
        ),
    ]
