# Generated by Django 2.2.6 on 2019-11-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_simpleactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleactivity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
