# Generated by Django 2.2.6 on 2019-11-06 12:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20191105_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='活动描述'),
        ),
    ]
