# Generated by Django 2.2.6 on 2019-11-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_simpleactivity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleactivity',
            name='uid',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='活动id'),
        ),
    ]
