# Generated by Django 2.2.6 on 2019-11-06 12:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20191106_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='活动描述'),
        ),
    ]
