# Generated by Django 2.2.6 on 2019-11-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20191106_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='activity/files/%Y/%m/%d/', verbose_name='活动策划表'),
        ),
    ]
