# Generated by Django 2.2.6 on 2019-11-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_simpleactivity_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simpleactivity',
            old_name='created_at',
            new_name='created',
        ),
    ]
