# Generated by Django 2.2.6 on 2019-11-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20191106_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.CharField(max_length=255, verbose_name='活动时间'),
        ),
    ]
