# Generated by Django 2.2.6 on 2019-11-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20191106_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_academy_verify',
            field=models.BooleanField(default=False, verbose_name='学院是否审核通过'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_school_verify',
            field=models.BooleanField(default=False, verbose_name='学校是否审核通过'),
        ),
    ]
