# Generated by Django 2.2.6 on 2019-12-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20191121_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='score_player',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='score_staff',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='score_viewer',
        ),
        migrations.RemoveField(
            model_name='simpleactivity',
            name='score_player',
        ),
        migrations.RemoveField(
            model_name='simpleactivity',
            name='score_staff',
        ),
        migrations.RemoveField(
            model_name='simpleactivity',
            name='score_viewer',
        ),
        migrations.AddField(
            model_name='activity',
            name='join_type',
            field=models.SmallIntegerField(default=0, verbose_name='参与身份'),
        ),
        migrations.AddField(
            model_name='activity',
            name='score',
            field=models.FloatField(default=0, verbose_name='学时'),
        ),
        migrations.AddField(
            model_name='simpleactivity',
            name='join_type',
            field=models.SmallIntegerField(default=0, verbose_name='参与身份'),
        ),
        migrations.AddField(
            model_name='simpleactivity',
            name='score',
            field=models.FloatField(default=0, verbose_name='学时'),
        ),
    ]
