# Generated by Django 2.2.6 on 2019-12-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_auto_20191203_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='join_type',
            field=models.SmallIntegerField(choices=[(1, '参赛者'), (2, '观众'), (3, '工作人员')], default=0, verbose_name='参与身份'),
        ),
        migrations.AlterField(
            model_name='simpleactivity',
            name='join_type',
            field=models.SmallIntegerField(choices=[(1, '参赛者'), (2, '观众'), (3, '工作人员')], default=0, verbose_name='参与身份'),
        ),
    ]
