# Generated by Django 2.2.6 on 2019-12-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20191203_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='nums',
            field=models.IntegerField(blank=True, help_text='可不填写', null=True, verbose_name='人数上限'),
        ),
        migrations.AlterField(
            model_name='simpleactivity',
            name='nums',
            field=models.IntegerField(blank=True, null=True, verbose_name='参加人数'),
        ),
    ]
