# Generated by Django 2.2.6 on 2019-12-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20191203_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='file',
            field=models.FileField(blank=True, help_text='请上传.doc或者.docx后缀的文档', null=True, upload_to='activity/files/%Y/%m/%d/', verbose_name='活动策划书'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='join_type',
            field=models.SmallIntegerField(choices=[(1, '参赛者'), (2, '观众'), (3, '工作人员')], default=2, verbose_name='参与身份'),
        ),
        migrations.AlterField(
            model_name='simpleactivity',
            name='join_type',
            field=models.SmallIntegerField(choices=[(1, '参赛者'), (2, '观众'), (3, '工作人员')], default=2, verbose_name='参与身份'),
        ),
    ]
