# Generated by Django 2.2.6 on 2019-11-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20191111_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_verifying',
            field=models.BooleanField(default=True, verbose_name='是否正在进行审核'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='logo',
            field=models.ImageField(default='', upload_to='activity/logo/%Y/%m/%d/', verbose_name='活动图标'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='sponsor',
            field=models.CharField(max_length=255, verbose_name='主办方'),
        ),
    ]
