# Generated by Django 2.2.6 on 2019-11-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_auto_20191112_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='reason',
            field=models.CharField(default='', max_length=255, verbose_name='审核失败原因'),
        ),
    ]
