# Generated by Django 2.2.6 on 2020-02-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_auto_20200228_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_craft',
            field=models.BooleanField(default=False, verbose_name='是否为草稿'),
        ),
    ]
