# Generated by Django 2.2.6 on 2019-11-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_auto_20191112_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-created_at',), 'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='is_academy_verify',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='is_school_verify',
        ),
    ]
