# Generated by Django 2.2.6 on 2019-11-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_auto_20191112_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='截止日期'),
        ),
        migrations.AlterModelTable(
            name='activity',
            table='activity_backend',
        ),
    ]
