# Generated by Django 2.2.6 on 2020-02-29 15:45

from django.db import migrations, models
import learntime.activity.models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_auto_20200229_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='credit_type',
            field=models.CharField(blank=True, choices=[('n', '请选择'), ('fl_credit', '法律'), ('wt_credit', '文体'), ('xl_credit', '心理'), ('cxcy_credit', '创新创业'), ('sxdd_credit', '思想道德')], default='n', max_length=20, null=True, verbose_name='学时类别'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='file',
            field=models.FileField(blank=True, help_text='请上传.doc或者.docx后缀的文档', null=True, upload_to=learntime.activity.models.upload_file, verbose_name='活动策划书'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=learntime.activity.models.upload_logo, verbose_name='活动图标'),
        ),
    ]
