# Generated by Django 2.2.6 on 2019-11-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_auto_20191115_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='stop',
            field=models.BooleanField(default=False, verbose_name='是否截止'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='报名截止日期'),
        ),
    ]
