# Generated by Django 2.2.6 on 2020-06-10 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_auto_20200610_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_for_verify_activities', to=settings.AUTH_USER_MODEL, verbose_name='院级审核者'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='to_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_waiting_for_verify_activities', to=settings.AUTH_USER_MODEL, verbose_name='校级审核者'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_activities', to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
    ]
