# Generated by Django 2.2.6 on 2019-10-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academy',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='学院'),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='年级'),
        ),
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.IntegerField(choices=[(1, 'root'), (2, 'school'), (3, 'academy'), (4, 'student')], default=1, verbose_name='身份'),
        ),
        migrations.AddField(
            model_name='user',
            name='klass',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
    ]
