# Generated by Django 2.2.6 on 2019-11-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('role',), 'verbose_name': '管理员', 'verbose_name_plural': '管理员'},
        ),
    ]
