# Generated by Django 2.2.6 on 2019-12-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191121_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.IntegerField(choices=[(1, '超级管理员'), (2, '校级'), (3, '院级'), (4, '学生干部级')], default=1, verbose_name='请求的身份'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, '超级管理员'), (2, '校级'), (3, '院级'), (4, '学生干部级')], default=4, verbose_name='权限'),
        ),
    ]
