# Generated by Django 2.2.6 on 2019-11-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_academy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, help_text='请按照格式填写，例如(2019级)', max_length=20, null=True, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='klass',
            field=models.CharField(blank=True, help_text='填写格式按照 <软件工程1班> 填写', max_length=20, null=True, verbose_name='班级'),
        ),
    ]
