# Generated by Django 2.2.6 on 2020-02-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191203_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_freeze',
            field=models.BooleanField(default=False, verbose_name='是否冻结'),
        ),
    ]
