# Generated by Django 2.2.6 on 2020-02-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_freeze'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identity',
        ),
    ]
