# Generated by Django 2.2.6 on 2020-04-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
    ]
