# Generated by Django 2.2.6 on 2020-04-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200412_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='社团协会'),
        ),
        migrations.AlterField(
            model_name='user',
            name='klass',
            field=models.CharField(blank=True, help_text='填写格式按照格式填写，例如(软件工程1班)', max_length=20, null=True, verbose_name='班级'),
        ),
    ]
