# Generated by Django 2.2.6 on 2020-06-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, '超级管理员'), (2, '校级'), (3, '院级'), (4, '学生干部级'), (5, '组织账号')], default=4, verbose_name='权限'),
        ),
    ]
