# Generated by Django 2.2.6 on 2020-02-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, verbose_name='学号')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('grade', models.CharField(default='', max_length=255, verbose_name='年级')),
                ('academy', models.CharField(default='', max_length=255, verbose_name='学院')),
                ('clazz', models.CharField(default='', max_length=255, verbose_name='班级')),
                ('credit', models.FloatField(default=0, verbose_name='学时')),
                ('cxcy_credit', models.FloatField(default=0, verbose_name='创新创业学时')),
                ('sxdd_credit', models.FloatField(default=0, verbose_name='思想道德学时')),
                ('fl_credit', models.FloatField(default=0, verbose_name='法律学时')),
                ('wt_credit', models.FloatField(default=0, verbose_name='文体学时')),
                ('xl_credit', models.FloatField(default=0, verbose_name='心理学时')),
                ('record_time', models.DateField(verbose_name='统计时间')),
            ],
            options={
                'verbose_name': '学时统计表',
                'verbose_name_plural': '学时统计表',
                'db_table': 'credit_stat',
            },
        ),
    ]
