# Generated by Django 2.2.6 on 2020-02-26 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditstat',
            name='id',
        ),
        migrations.AddField(
            model_name='creditstat',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='活动id'),
        ),
    ]
