# Generated by Django 2.2.6 on 2020-02-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_auto_20200226_1427'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='creditstat',
            index=models.Index(fields=['uid'], name='uid_idx'),
        ),
    ]
