# Generated by Django 2.2.6 on 2020-02-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_auto_20200226_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditstat',
            name='diff',
            field=models.FloatField(default=0, verbose_name='总学时月度变化'),
        ),
        migrations.AddField(
            model_name='creditstat',
            name='diff_cxcy',
            field=models.FloatField(default=0, verbose_name='创新创业学时月度变化'),
        ),
        migrations.AddField(
            model_name='creditstat',
            name='diff_fl',
            field=models.FloatField(default=0, verbose_name='法律学时月度变化'),
        ),
        migrations.AddField(
            model_name='creditstat',
            name='diff_sxdd',
            field=models.FloatField(default=0, verbose_name='思想道德学时月度变化'),
        ),
        migrations.AddField(
            model_name='creditstat',
            name='diff_wt',
            field=models.FloatField(default=0, verbose_name='文体学时月度变化'),
        ),
        migrations.AddField(
            model_name='creditstat',
            name='diff_xl',
            field=models.FloatField(default=0, verbose_name='心理学时月度变化'),
        ),
        migrations.AlterField(
            model_name='creditstat',
            name='record_time',
            field=models.DateField(verbose_name='统计时间(上个月)'),
        ),
    ]
