# Generated by Django 2.2.6 on 2020-02-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_auto_20200229_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditstat',
            options={'ordering': ('-record_time',), 'verbose_name': '学时统计表', 'verbose_name_plural': '学时统计表'},
        ),
    ]
