# Generated by Django 2.2.6 on 2020-02-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalconf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configration',
            name='default_password',
            field=models.CharField(default='123456', max_length=20, verbose_name='管理员默认密码'),
        ),
    ]
