# Generated by Django 2.2.6 on 2020-02-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalconf', '0002_configration_default_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='configration',
            name='maintenance_notice',
            field=models.TextField(default='', verbose_name='维护提示'),
        ),
        migrations.AlterField(
            model_name='configration',
            name='is_maintenance',
            field=models.BooleanField(default=False, verbose_name='维护'),
        ),
    ]
