# Generated by Django 2.2.6 on 2020-02-28 12:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalconf', '0004_auto_20200227_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '帮助文档',
                'verbose_name_plural': '帮助文档',
            },
        ),
        migrations.AddIndex(
            model_name='help',
            index=models.Index(fields=['category'], name='category_idx'),
        ),
    ]
