# Generated by Django 2.2.6 on 2019-11-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='clazz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='年级'),
        ),
    ]
