# Generated by Django 2.2.6 on 2019-11-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_simplestudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplestudent',
            name='email',
            field=models.CharField(default='', max_length=50, verbose_name='邮箱'),
        ),
    ]
