# Generated by Django 2.2.6 on 2019-11-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20191104_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='其他信息'),
        ),
    ]
