# Generated by Django 2.2.6 on 2019-11-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20191104_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=255, verbose_name='密码'),
        ),
    ]
