# Generated by Django 2.2.6 on 2020-01-16 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0003_simplestudent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfile',
            name='excel_file',
            field=models.FileField(upload_to='student/%Y/%m/%d/', verbose_name='请选择文件'),
        ),
        migrations.CreateModel(
            name='StudentCreditVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=50, verbose_name='活动名称')),
                ('sponsor', models.CharField(max_length=20, verbose_name='主办方')),
                ('uid', models.CharField(max_length=20, verbose_name='学号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('academy', models.CharField(max_length=20, verbose_name='学院')),
                ('clazz', models.CharField(max_length=20, verbose_name='班级')),
                ('join_type', models.CharField(max_length=20, verbose_name='参加类型')),
                ('award', models.CharField(max_length=20, verbose_name='获奖情况')),
                ('credit_type', models.CharField(max_length=20, verbose_name='认定项目')),
                ('credit', models.FloatField(default=0, verbose_name='认定活动时')),
                ('contact', models.CharField(max_length=50, verbose_name='填报人及联系方式')),
                ('to_name', models.CharField(max_length=20, verbose_name='审核人')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
                ('verify', models.BooleanField(default=False, verbose_name='是否审核')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_to_verify_credits', to=settings.AUTH_USER_MODEL, verbose_name='审核者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applying_to_verify_credits', to=settings.AUTH_USER_MODEL, verbose_name='填写学时补录的管理员')),
            ],
            options={
                'verbose_name': '请求加学时',
                'verbose_name_plural': '请求加学时',
                'db_table': 'student_credit_verify',
                'ordering': ('-created_at',),
            },
        ),
    ]
