# Generated by Django 2.2.6 on 2019-12-04 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0003_simplestudent_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCreditVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, verbose_name='学号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('credit', models.FloatField(default=0, verbose_name='学时数')),
                ('verify', models.BooleanField(default=False, verbose_name='是否审核')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='waiting_to_verify_credits', to=settings.AUTH_USER_MODEL, verbose_name='审核者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applying_to_verify_credits', to=settings.AUTH_USER_MODEL, verbose_name='请求加学时者')),
            ],
            options={
                'verbose_name': '请求加学时',
                'verbose_name_plural': '请求加学时',
                'db_table': 'student_credit_verify',
                'ordering': ('-created_at',),
            },
        ),
    ]
