# Generated by Django 2.2.6 on 2020-01-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200116_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcreditverify',
            options={'ordering': ('created_at',), 'verbose_name': '请求加学时', 'verbose_name_plural': '请求加学时'},
        ),
    ]
