# Generated by Django 2.2.6 on 2019-11-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.CharField(help_text='学号', max_length=255, primary_key=True, serialize=False, verbose_name='学号'),
        ),
    ]
