# Generated by Django 2.2.6 on 2019-12-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentcreditverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcreditverify',
            name='credit_type',
            field=models.IntegerField(choices=[(0, '未选择'), (1, '法律学时'), (2, '文体学时'), (3, '心理学时'), (4, '创新创业学时'), (5, '思想道德学时')], default=0, verbose_name='学时类别'),
        ),
        migrations.AlterField(
            model_name='studentcreditverify',
            name='credit',
            field=models.FloatField(default=0, verbose_name='增加学时'),
        ),
    ]
