# Generated by Django 2.2.6 on 2020-06-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200118_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplestudent',
            name='cxcy_credit',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='创新创业素质'),
        ),
        migrations.AlterField(
            model_name='simplestudent',
            name='fl_credit',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='法律素养'),
        ),
        migrations.AlterField(
            model_name='simplestudent',
            name='sxdd_credit',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='思想道德素质'),
        ),
        migrations.AlterField(
            model_name='simplestudent',
            name='wt_credit',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='文体素质'),
        ),
        migrations.AlterField(
            model_name='simplestudent',
            name='xl_credit',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='身心素质'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cxcy_credit',
            field=models.FloatField(default=0, verbose_name='创新创业素质'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fl_credit',
            field=models.FloatField(default=0, verbose_name='法律素养'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sxdd_credit',
            field=models.FloatField(default=0, verbose_name='思想道德素质'),
        ),
        migrations.AlterField(
            model_name='student',
            name='wt_credit',
            field=models.FloatField(default=0, verbose_name='文体素质'),
        ),
        migrations.AlterField(
            model_name='student',
            name='xl_credit',
            field=models.FloatField(default=0, verbose_name='身心素质'),
        ),
    ]
