# Generated by Django 2.2.6 on 2019-11-04 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='info',
        ),
    ]
