# Generated by Django 2.2.6 on 2020-06-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200608_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('uid',), 'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
    ]
