# Generated by Django 2.2.6 on 2020-06-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200611_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcreditverify',
            name='activity_name',
            field=models.CharField(max_length=100, verbose_name='活动名称'),
        ),
        migrations.AlterField(
            model_name='studentcreditverify',
            name='contact',
            field=models.CharField(max_length=255, verbose_name='填报人及联系方式'),
        ),
        migrations.AlterField(
            model_name='studentcreditverify',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='studentcreditverify',
            name='sponsor',
            field=models.CharField(max_length=255, verbose_name='主办方'),
        ),
    ]
