# Generated by Django 2.2.6 on 2020-10-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_studentcreditverify_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcreditverify',
            name='fail_reason',
            field=models.CharField(default='', max_length=50, verbose_name='导入错误的原因'),
        ),
        migrations.AddField(
            model_name='studentcreditverify',
            name='is_fail',
            field=models.BooleanField(default=False, verbose_name='是否导入失败'),
        ),
    ]
