# Generated by Django 2.2.6 on 2019-11-15 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20191106_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student_backend',
        ),
    ]
